# ansible-playbook -i hosts playbook-managernode.yml
# aws --region us-west-2 ec2 create-tags --resources i-0914892a3bac5ff82 --tags "Key=Name,Value=Web01"

# ansible-playbook -i file_vars.yml playbook-config-nodes.yml

# sudo docker node ls
# sudo docker swarm leave --force

- name: managernode
  hosts: managernode
  gather_facts: no
  remote_user: centos
  vars_files:
    file_vars.yml
  tasks:

    # ***

    - name: shell command
      shell: |
        sudo hostnamectl set-hostname managernode
        sudo chmod 777 /etc/hosts
        
    - name: write host file
      shell: |
        sudo echo "{{ managernode_private_ip }} managernode" >> /etc/hosts
        sudo echo "{{ workernode1_private_ip }} workernode1" >> /etc/hosts

    - name: change permission back to be -rw-r--r-- 
      shell: sudo chmod 644 /etc/hosts
    # ***


    # - import_tasks: file_resue_tasks.yml

    - name: run Docker Swarm join
      shell: |
        line=`sudo docker swarm init`
        var="${line:142}"
        var="${var%T*}"
        echo $var
      register: K8S_TOKEN
      
    - name: register a variable
      add_host:
        name:   "K8S_TOKEN_HOLDER"
        token:  "{{ K8S_TOKEN.stdout }}"
        # name:   "CREATE_A_SWARM"
        # token:  "{{ COMMAND.stdout_lines }}"   # https://stackoverflow.com/questions/33896847/how-do-i-set-register-a-variable-to-persist-between-plays-in-ansible
        



- name: workernode1
  hosts: workernode1
  gather_facts: no
  remote_user: centos
  vars_files:
    file_vars.yml
  tasks:

  # ***
    - name: shell command
      shell: |
        sudo hostnamectl set-hostname workernode1
        sudo chmod 777 /etc/hosts
        
    - name: write host file
      shell: |
        sudo echo "{{ managernode_private_ip }} managernode" >> /etc/hosts
        sudo echo "{{ workernode1_private_ip }} workernode1" >> /etc/hosts

    - name: change permission back to be -rw-r--r-- 
      shell: sudo chmod 644 /etc/hosts
    # ***

    - name: show register a variable
      debug:
        msg: "{{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

    # - import_tasks: file_resue_tasks.yml

    - name: join the Docker Swarm
      shell: |
        sudo {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}
      
