---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  vars_files:
    - variables/encrypt-iam-account.yml
  tasks:
    - name: run instance
      ec2:
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}" 
         key_name: "keypair-for-ansible"
         instance_type: "t2.micro"
         image: "ami-9abea4fb"
         wait: yes
         group_id: "sg-14e5924e"
         wait_timeout: 500
         count: "1"
         instance_tags:
           Name: "Nginx"
           Service: "reverseproxy"
         vpc_subnet_id: "subnet-09678117a9fb4f6f1"
         region: "us-west-2"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # we attach a variable to "demogroup", We don't want to confirm the key validation
      ansible_ssh_private_key_file: keypair-for-ansible.pem
      with_items: ec2.instances 

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

# - hosts: launched
#   vars:
#     ansible_ssh_private_key_file: ~/.ssh/ansible_ec2.pem
#   gather_facts: true
#   user: ubuntu
#   become: yes
#   become_method: sudo
#   become_user: root
#   roles:
#     - motd 
#     - javaubuntu
#     - apt-get
#     - nginx