# source /Users/jam/bin/activate

# sudo docker node ls
# sudo docker service ps webservice
# sudo docker swarm leave --force
# ansible-playbook -i vars-hosts.yml playbook-config-nodes.yml


  ####################################################################
  #                                                                  #
  #    Configure Manager Node                                        #
  #                                                                  # 
  ####################################################################
- name: Configure Manager Node
  hosts: managernode
  gather_facts: no
  remote_user: centos
  vars_files:
    vars-hosts.yml
  tasks:

    - name: managernode - set hostname
      shell: sudo hostnamectl set-hostname managernode

    - name: managernode - include task 
      include_tasks: reuse-tasks.yml


    - name: managernode - initialize a Swarm # This will grab only the token-string by Shell script, in order to assign to the WorkerNode.
      shell: |
        line=`sudo docker swarm init`
        var="${line:142}"
        var="${var%T*}"
        echo $var
      register: SWARM_TOKEN
      
    - name: managernode - register a variable
      add_host:
        name:   "REGISTER_VARIABLE"
        token:  "{{ SWARM_TOKEN.stdout }}"     # Ref: https://stackoverflow.com/questions/33896847/how-do-i-set-register-a-variable-to-persist-between-plays-in-ansible
        

  ####################################################################
  #                                                                  #
  #    Configure Worker Node                                         #
  #                                                                  # 
  ####################################################################
- name: Configure Worker Node
  hosts: workernode
  gather_facts: no
  remote_user: centos
  vars_files:
    vars-hosts.yml
  tasks:

    - name: workernode - set hostname
      shell: sudo hostnamectl set-hostname workernode

    - name: workernode - include task 
      include_tasks: reuse-tasks.yml

    - name: workernode - show register a variable
      debug:
        msg: "{{ hostvars['REGISTER_VARIABLE']['token'] }}"
  
    - name: workernode - join the Docker Swarm
      shell: |
        sudo {{ hostvars['REGISTER_VARIABLE']['token'] }}
      

  ####################################################################
  #                                                                  #
  #    Deploy service at Manager Node                                #
  #                                                                  # 
  ####################################################################
- name: Deploy service at Manager Node
  hosts: managernode
  gather_facts: no
  remote_user: centos
  vars_files:
    vars-hosts.yml
  tasks:

    - name: deploy - deploy webservice
      shell: |
        sudo docker service create -p 80:80 --name webservice --replicas 5 httpd

